添加了新的方法，只在激怒可用时变熊
alawing/WhitePaws pull request #25
Opened 2022-11-05 03:51 UTC by discountry

1. 团本中满buff状态下猫形态普工收益更高，且熊猫转换时有概率卡普攻导致变熊后怒气不足
2. 目前的方法，如果熊形态第一次普攻出发了清晰预兆，会马上切换回猫形态，相当于浪费了两个公共CD

添加了新的方法：

jnbxjgx （激怒变形金刚熊）

判断：

GetSpellCooldown(5229) == 0

激怒技能可用时才变熊，降低变身频率，解决卡怒气问题。

2022-11-08 06:50 UTC, alawing commented
我是计划在之后版本中可以用户自定义监控的buff和debuff列表。可以在setting里设置。现在还在想怎么设计，你有什么想法？

2022-11-10 06:32 UTC, discountry commented
> 我是计划在之后版本中可以用户自定义监控的buff和debuff列表。可以在setting里设置。现在还在想怎么设计，你有什么想法？

单纯开关的话，加几个变量改true false就好了。
如果是进一步改善功能，我是想加入动态判断能量，而不是写死。
比方说如果猫形态能量彻底打空了，那么肯定是优先变熊，而如果只是刚刚低于27，没有激怒，则不变熊。
熊形态下如果猫能量不够打一个技能，即使触发清晰预兆也最好不变，否则等于浪费了两个GCD等…
另外现在考虑了下一跳回能时间没有？

2022-11-17 22:40 UTC, alawing requested changes
I have left some comments.

2022-11-17 22:40 UTC, alawing commented on Libs/wcCore.lua
> +	if (wc.getBuff(16870) and wc.getRage() < 25) or wc.getCoolDown(50213) < 2 then
Rage你的意思是如果清晰预兆触发了并且怒气不足，就返回没有足够能量，就不回猫吧？
那应该是(wc.getBuff(16870) and wc.getRage() >= 25) 如果触发清晰预兆并且怒气大于25，就返回有足够能量，就可以回猫，反之保持熊，用让熊消耗掉清晰预兆，是这样吧？
猛虎cooldown should be 3？避免变身过去猛虎没了再变回来，一共3秒。

2022-11-17 22:40 UTC, alawing commented on Libs/wcCore.lua
> +-- 清洗预兆 16870
清晰

2022-11-17 22:40 UTC, alawing commented on WhitePaws.lua
> +	if not wc.strongControl and wc.enoughMana() and not wc.getShiftGCD() and not wc.enoughEnergy(e) and not wc.getBuff(50334) and wc.getBuffTime(52610) > 5 and wc.getComboPoint() < 4 then
这里是想表达如果马上可以续猛虎，那么就不变熊吗？
标准化一下时间？变身过去放个技能变身回来是1.5+1.5+1 = 4秒，所以猛虎最极限是4？
还有combo意思是如果4，5星就不变熊吗？

2022-11-18 17:16 UTC, discountry commented on Libs/wcCore.lua
> +	if (wc.getBuff(16870) and wc.getRage() < 25) or wc.getCoolDown(50213) < 2 then
如果怒气>25，表示可以同时打出重殴+一个技能，因此即使触发了清晰预兆也不能变猫，继续保持在熊形态。

2022-11-18 17:18 UTC, discountry commented on Libs/wcCore.lua
> +	if (wc.getBuff(16870) and wc.getRage() < 25) or wc.getCoolDown(50213) < 2 then
猛虎自身不占用公CD，变身1.5s公CD，变身后还有0.5秒准备打出下一个攻击技能。

2023-03-16 18:46 UTC, merged